[package]
name = "hexie"
version = "0.1.0"
authors = ["Sam <samwho@lbak.co.uk>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
hex = "0.3.2"
log = "0.4.6"
env_logger = "0.6.1"
termion = "1.5.2"
atty = "0.2.11"
streaming-stats = "0.2.2"
pager = "0.15.0"
term_size = "0.3.1"